# Generated by Django 5.2.1 on 2025-06-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonfordb',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='lessonfordb',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='lessonfordb',
            index=models.Index(fields=['-time_create'], name='lesson_1_le_time_cr_2b11ab_idx'),
        ),
    ]
