# Generated by Django 5.2.1 on 2025-06-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0003_alter_lessonfordb_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonfordb',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
