# Generated by Django 5.2.1 on 2025-06-10 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0005_category_lessonfordb_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonfordb',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lesson_1.category'),
        ),
    ]
